### ISSUE TITLE
automate update

### ISSUE THREAD

**Issue by maxogden** [mafintosh/electron-prebuilt#16]
we need a command to run that:

- increments package.json to new version
- updates index.js to have new version (we could prob just have it read package.json)
- commits and tags the commit with the new version (like what `npm version patch` does)

the command should be e.g. 'node update.js 0.26.0'

then they can use it here https://github.com/atom/electron/issues/1488 to automate

**Comment by bcomnes** [comment]
Help wanted?

**Comment by maxogden** [comment]
@bcomnes yes, help wanted :)

**Comment by johnmuhl** [comment]
I took a stab at this using GitHub webhooks and a web service https://github.com/johnmuhl/electron-prebuilt-updater. Thoughts on this approach?

**Comment by maxogden** [comment]
@johnmuhl EXCELLENT! I'm setting it up now. Just to clarify for https://github.com/johnmuhl/electron-prebuilt-updater#setup-the-webhook I am going to need someone who is an Owner on https://github.com/atom/electron to set up a new webhook and choose a secret, right?

**Comment by johnmuhl** [comment]
@maxogden That is correct. I asked about it in atom/electron#1488. I just setup my own fork of electron to test with.

**Comment by maxogden** [comment]
@johnmuhl ok excellent. I didn't see that comment till just now. I just set up an instance with my credentials on heroku, and i've pinged a GH employee about getting the webhook added. Super useful!

**Comment by johnmuhl** [comment]
One more thing to note is that the web service only updates `package.json`; so it's dependent on #39 or something like it getting merged. The updater could also be changed to make changes to both files if making two commits per version bump is ok.

**Comment by maxogden** [comment]
OK should be all good to go now! thanks @johnmuhl i'll let you know when the first successful release happens. only thing thats missing from your repo is better failure logging etc in case something doesn't work

**Comment by johnmuhl** [comment]
@maxogden I've improved the error logging now. Thanks for your help making it happen.
