### ISSUE TITLE
tags don't match versions on npm

### ISSUE THREAD

**Issue by ngoldman** [mafintosh/electron-prebuilt#17]
* versions on npm: `[ '0.24.0', '0.25.0', '0.25.1-1', '0.25.1' ]`
* tags on github: `v1.0.0`...`v1.2.1`

**Comment by maxogden** [comment]
YA that's cause I suck at git

**Comment by ngoldman** [comment]
I :heart: obsessing over tags and releases, lmk if I can help

**Comment by maxogden** [comment]
i apparently never git push --tags. i just did and maybe fixed this. dunno really

**Comment by ngoldman** [comment]
3/4 are there now https://github.com/mafintosh/electron-prebuilt/releases (`0.25.1-1` ain't), but all the pre-npm publish stuff too.

**Comment by mafintosh** [comment]
@ngoldman i've added you as collab so you can tag the remaining releases if you want

**Comment by RnbWd** [comment]
I just put this in my path, I can't remember where I found it.

```
# NPM Publishing
alias patch='pre-version && npm version patch && post-version'
alias minor='pre-version && npm version minor && post-version'
alias major='pre-version && npm version major && post-version'
alias pre-version='git diff --exit-code && npm prune && npm install -q && npm test'
alias post-version='npm run --if-present build && git diff --exit-code && git push && git push --tags && npm publish'
```

**Comment by ngoldman** [comment]
:+1:
