### ISSUE TITLE
install in home directory? [almost pull request]

### ISSUE THREAD

**Issue by RnbWd** [mafintosh/electron-prebuilt#22]
:zap: `Electron` is fun to play with, especially with the recent growth of apps. Between experimenting and modifying apps, `electron-prebuilt` started downloading lots of :floppy_disk: on my machine. But I only want one copy, so I forked the lib and named it [electron-bin](https://github.com/RnbWd/electron-bin). I felt like the changes might break other apps and don't address any major bugs, so I didn't submit a PR:

**Difs:**

Downloads electron in home directory - `~/.electron/<version>/.../electron` - checks for it's existence before starting any downloads, and `rimrafs` the `.zip` after download. Also added `electronVersion` field in the `package.json` for convenience.

**PR potential?**

If `~/.electron/` is treated as a cache, with the files copied into the local `node_modules/electron-prebuilt/dest` folder, the behavior might be similar enough to not break anything. Let me know if there's PR interest because these libs are almost identical!!

**Comment by mafintosh** [comment]
Does your thing copy the electron binary into the locally installed dep? If so I'm fine with a shared cache.

**Comment by RnbWd** [comment]
No, it doesn't copy the binary into the locally installed dep. It's definitely possible. [home-path](https://github.com/75lb/home-path) is cross platform, the only questions I have are:

1) is `.electron` a safe namespace? 

2)  symlinks? or full copies? (I assume copies)

**Comment by RnbWd** [comment]
figured it out - https://github.com/mafintosh/electron-prebuilt/pull/23
 
- `nugget` downloads zip into home directory `~/.electron` 
- `extract-zip` works identical but sources from the cache 
- if .zip already exists, no need to download, just `extract-zip`

simple

**Comment by RnbWd** [comment]
The other lib (`electron-bin`) will use `bin-link` that focuses on cmd-line usage of single binary (-g)
