### ISSUE TITLE
Failed at the electron-prebuilt@0.25.3-2 install script 'node install.js'

### ISSUE THREAD

**Issue by nomosyn** [mafintosh/electron-prebuilt#27]
`$ sudo npm install electron-prebuilt -g` fails (see log below)

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion: 10.10.3
BuildVersion: 14D136

$ npm -v
2.7.4
```

[npm-debug.log](https://gist.github.com/nomosyn/8c9068c9b4f06f9257e6)

**Comment by greco** [comment]
me too, but on windows 7

io.js
$npm -v
2.9.0

**Comment by RnbWd** [comment]
There have been a few changes in how this library it downloads files recently, and it exists in a separate repo now: https://github.com/maxogden/electron-download 

Maybe, try deleting the node_modules folder (for electron-prebuilt), and using `npm-install` again. There might have been small hiccups with the electron download path? I haven't followed closely but they're listed as closed PR's in the `electron-download` repo linked above

**Comment by greco** [comment]
my npm debug log 
zip(132kb)
http://pan.baidu.com/s/1jG7XqEM

**Comment by RnbWd** [comment]
@greco looks like a path issue in windows. - https://stackoverflow.com/questions/28425229/why-cant-execute-npm-start-or-even-other-npm-commands

Most of the dev's working on this project use macs (I think), so I can't say if it's a path issue that's solvable in windows, or if our attempt to download zips into [user-home](https://github.com/sindresorhus/user-home/blob/master/index.js) (source code) path, it *should* work on windows but it could be funky

**Comment by greco** [comment]
Thanks @RnbWd , I'll try it

**Comment by greco** [comment]
i'm deleted "electron-v0.25.3-win32-x64.zip" in my home folder(@C:\Users\Greco\.electron)

and then run command "npm i electron-prebuilt --save-dev" , it's ok,worked!

so, may be the zip file is not complete

**Comment by bobpappas** [comment]
Same problem on Mac:

7209 error Darwin 14.0.0
7210 error argv "node" "/usr/local/bin/npm" "install" "electron-prebuilt" "-g" "--verbose"
7211 error node v0.12.2
7212 error npm  v2.7.4
7213 error code ELIFECYCLE
7214 error electron-prebuilt@0.25.3-2 install: `node install.js`
7214 error Exit status 1
7215 error Failed at the electron-prebuilt@0.25.3-2 install script 'node install.js'.
7215 error This is most likely a problem with the electron-prebuilt package,
7215 error not with npm itself.
7215 error Tell the author that this fails on your system:
7215 error     node install.js
7215 error You can get their info via:
7215 error     npm owner ls electron-prebuilt
7215 error There is likely additional logging output above.

**Comment by mafintosh** [comment]
@bobpappas could you copy the entire command line output?

**Comment by NathanJang** [comment]
I've tried installing the new 0.26.0 now, with the same issue. [npm-debug.log](https://gist.github.com/NathanJang/98c9901dfcecec3efa14)

**Comment by mafintosh** [comment]
@NathanJang i need the cli output. npm-debug.log unfortunately doesn't help us as this is probably a problem with downloading the binary in the install script

**Comment by NathanJang** [comment]
```
~/G/P/SRT-signup (master) $ npm install --save-dev electron-prebuilt 
-
> electron-prebuilt@0.26.0 install /Users/jonchan/Gits/Private/SRT-signup/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.26.0-darwin-x64.zip
[=================================================>] 100.0% (1.79 MB/s)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: invalid central directory file header signature: 0xe03a4436
    at /Users/jonchan/Gits/Private/SRT-signup/node_modules/electron-prebuilt/node_modules/extract-zip/node_modules/yauzl/index.js:157:70
    at /Users/jonchan/Gits/Private/SRT-signup/node_modules/electron-prebuilt/node_modules/extract-zip/node_modules/yauzl/index.js:342:5
    at /Users/jonchan/Gits/Private/SRT-signup/node_modules/electron-prebuilt/node_modules/extract-zip/node_modules/yauzl/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:527:17)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save-dev" "electron-prebuilt"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.26.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.26.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jonchan/Gits/Private/SRT-signup/npm-debug.log
```
@mafintosh here you go

**Comment by mafintosh** [comment]
@NathanJang thanks! does it work if you try again?

**Comment by NathanJang** [comment]
@mafintosh nope, exactly the same error unfortunately. Thanks for your help!

**Comment by mafintosh** [comment]
@NathanJang try deleting `~/.electron` and try again - i'm curious if that works

**Comment by NathanJang** [comment]
@mafintosh 
```
~/G/P/SRT-signup (master) $ npm install --save-dev electron-prebuilt 
|
> electron-prebuilt@0.26.0 install /Users/jonchan/Gits/Private/SRT-signup/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.26.0-darwin-x64.zip
[=================================================>] 100.0% (550.36 kB/s)
electron-prebuilt@0.26.0 node_modules/electron-prebuilt
├── extract-zip@1.0.3 (debug@0.7.4, minimist@0.1.0, mkdirp@0.5.0, yauzl@2.3.0, concat-stream@1.4.8, through2@0.6.3)
└── electron-download@1.0.4 (path-exists@1.0.0, home-path@0.1.1, mkdirp@0.5.0, mv@2.0.3, nugget@1.5.1)
```
It worked this time, thanks! :smile:

**Comment by mafintosh** [comment]
@NathanJang was this after your removed `~/.electron`?

**Comment by NathanJang** [comment]
@mafintosh yes

**Comment by maxogden** [comment]
@mafintosh @sindresorhus check out https://github.com/atom/electron/issues/1709#issuecomment-102712151, is it possible a user wouldn't have permission to create a folder in their own home directory? Maybe `node install.js` is getting spawned with the wrong permissions or something?

**Comment by mafintosh** [comment]
@maxogden i think he would need to run it with `--unsafe-perm` for it to work since he's root and npm runs stuff as `nobody`

**Comment by maxogden** [comment]
@mafintosh hmm I wonder we can do to make this problem go away

**Comment by mafintosh** [comment]
@maxogden to fix the `EACCESS` one, we could detect if you have write access to the cache (by writing a dummy file) and if not just write directly to the module folder as we used to do.

**Comment by RnbWd** [comment]
Two potential issues causes this:

1) Anyone who downloaded a version of electron-prebuilt prior to tempdir was implemented, and tried downloading but didn't finish the download, will be affected by this (low number hopefully).

2) But, this happened in 0.26 after it should have been fixed. There's (*maybe*) an issue with npm's cache resolution not caring about electron-download versions ^1.0.x. I recommended depreciated and upgrading versions here - [#4](https://github.com/maxogden/electron-download/issues/4). 

Either way I think it *should* only impact a handful of developers and deleting `~/.electron` seems to be the solution.

**Comment by RnbWd** [comment]
Also prior to electron-download I was deleting the the electron cache on all errors - (obviously not ideal), but it would fix this situation. Ideally deleting the cache for more specific errors is the right way to implement, but I'm not as competent as y'all regarding this.

**Comment by RnbWd** [comment]
> Uninstalling and re-installing nodejs and npm from my system fixed the issue for me. Thanks

In response to @mafintosh 

> check out [atom/electron#1709 (comment)](https://github.com/atom/electron/issues/1709#issuecomment-102712151)

root/.electron could be an issue, but for all we know deleting `.electron` could have worked the same as reinstalling node/npm?

**Comment by datoulei** [comment]
Error: EACCES, rename '/usr/local/lib/node_modules/electron-prebuilt/electron-tmp-download/electron-v0.26.0-darwin-x64.zip'
    at Error (native)

**Comment by MaliceMaikel** [comment]
I had this error. It was resolved after I updated NPM from 2.7 to 2.10.

sudo npm install npm -g 

Before I updated I noticed that I was able to use
npm install electron-prebuilt --save-dev, but wasn't able to install it globally using -g.
I saw the comment that removing .electron might fix it so I wanted to try that.
But there was no .electron map for me. I had to manually create .electron.
After that I was able to download the binary but not install it.

I got the EACCESS error everybody else seemed to be having.
Like I mentioned earlier I fixed that by running 

sudo npm install npm -g

**Comment by flaviocopes** [comment]
The main problem I think is the script cannot create `.electron/`. I created it manually and the global install worked :+1:

**Comment by operando** [comment]
I was able to install in the  following command.

mkdir .electron
chmod 777 .electron/
npm -g install electron-prebuilt

**Comment by capouch** [comment]
Upgrading npm and performing the above (operando) hack worked just fine for me, too.

**Comment by nomosyn** [comment]
Me too!

**Comment by jakefb** [comment]
I have tried reinstalling nodejs and npm and changing the permissions of ~/.electron with chmod 777. When I run sudo npm install electron-prebuilt -g I still get:

/usr/lib/node_modules/electron-prebuilt/install.js:15
  throw err
        ^
Error: EACCES, mkdir '/root/.electron'

I'm running Debian 8

**Comment by capouch** [comment]
Double-check your permissions on /root/.electron.

**Comment by jakefb** [comment]
I didn't have /root/.electron so I created it. The permissions for /root/.electron are drwxr-xr-x. What should they be?

**Comment by capouch** [comment]
drwxrwxrwx  2 root root 4096 May 24 16:06 .electron

**Comment by barwinco** [comment]
```
→ node --version
v0.12.4

→ npm --version
2.10.1

→ ls -la /root/ | grep .electron
drwxrwxrwx   2 root root    4096 May 26 12:10 .electron

→ sudo npm install -g electron-prebuilt
/usr/bin/electron -> /usr/lib64/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@0.26.1 postinstall /usr/lib64/node_modules/electron-prebuilt
> node install.js

/usr/lib64/node_modules/electron-prebuilt/install.js:15
  throw err
        ^
Error: EACCES, mkdir '/root/.electron'
    at Error (native)
npm ERR! Linux 4.0.4-gentoo
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "electron-prebuilt"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
```
:cry: :sob: :crying_cat_face:

**Comment by jclohmann** [comment]
I'm getting the same error, barwinco gets.

In a docker-container (as root):

-> iojs --version
v2.1.0

-> ls -la /root
total 20
drwx------  3 root root 4096 May 26 09:55 .
drwxr-xr-x 56 root root 4096 May 26 09:55 ..
-rw-r--r--  1 root root 3106 Feb 20  2014 .bashrc
drwxrwxrwx  2 root root 4096 May 26 09:55 .electron
-rw-r--r--  1 root root  140 Feb 20  2014 .profile

-> npm install electron-prebuilt -g
/usr/bin/electron -> /usr/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@0.26.1 postinstall /usr/lib/node_modules/electron-prebuilt
> node install.js

/usr/lib/node_modules/electron-prebuilt/install.js:15
  throw err
        ^
Error: EACCES: permission denied, mkdir '/root/.electron'
    at Error (native)
npm ERR! Linux 3.16.0-0.bpo.4-amd64
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "install" "electron-prebuilt" "-g"
npm ERR! node v2.1.0
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.26.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.26.1 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

**Comment by jakefb** [comment]
Same here, making the permissions of /root/.electron drwxrwxrwx didn't fix the problem for me either. Hopefully this gets fixed soon!

**Comment by maxogden** [comment]
So far we haven't been able to reproduce the problem. If anyone has steps to reproduce then we can fix it. I tested this on a fresh debian jessie image w/ iojs 2.1.0 yesterday and it worked fine for me, and it has also worked on 3 ubuntu boxes. 

@jclohmann could you share your dockerfile?

**Comment by maxogden** [comment]
Also if anyone on a system that can reproduce the failure wants to poke around, here is the line that is causing the problem: https://github.com/maxogden/electron-download/blob/a894734d2820d489836ecaa6f6a0c17712ad9516/index.js#L26. As you can see it's a simple `mkdir` call. I'm not sure why this is failing on a small percentage of linux machines, but maybe someone can figure it out.

You can do this to reproduce from source:

```
git clone https://github.com/mafintosh/electron-prebuilt.git
cd electron-prebuilt
npm link
```

And it should fail

Then you can edit `node_modules/electron-download/index.js` to modify the download script to try and make it work

**Comment by jclohmann** [comment]
I've extracted this from my Dockerfiles:
```
FROM ubuntu:14.10

# set company-proxy
# ENV http_proxy http://XXXXXXX/
# ENV https_proxy http://XXXXXXX/
# ENV no_proxy localhost, 127.0.0.1, company.de, .company.de

# RUN echo "Acquire::http::Proxy \"$http_proxy\";" >> /etc/apt/apt.conf && \
#	  echo "Acquire::https::Proxy \"$https_proxy\";" >> /etc/apt/apt.conf

# install iojs
RUN apt-get install -y wget

RUN wget "https://deb.nodesource.com/setup_iojs_2.x" && chmod +x setup_iojs_2.x && ./setup_iojs_2.x
RUN apt-get update && apt-get install iojs -fy

# apply operando's hack
RUN mkdir /root/.electron && \
	chmod 777 /root/.electron && \
	ls -la /root

# try to install electron
RUN npm install electron-prebuilt -g
```

Hopefully you can reproduce this.

**Comment by maxogden** [comment]
@jclohmann awesome, reproduced! will look into a fix...

**Comment by maxogden** [comment]
ah looks like `process.env.HOME` is `/`. weird

```
root@af3586b6b1c7:/# node
> process.env
{ HOSTNAME: 'af3586b6b1c7',
  TERM: 'xterm',
  PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  PWD: '/',
  SHLVL: '1',
  HOME: '/',
  _: '/usr/bin/node' }
```

**Comment by maxogden** [comment]
whats weird is that I have 14.04 installed on my server and I get this:

```
root@burrito:/media/cluster/containers/electron-bug# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
root@burrito:/media/cluster/containers/electron-bug# whoami
root
root@burrito:/media/cluster/containers/electron-bug# node -pe "process.env.HOME"
/root
```

@mafintosh what do you think of this:

if the mkdir fails, we catch the error and try to mkdir `./.electron` instead. if that fails then we throw

**Comment by maxogden** [comment]
@jclohmann ok published a new version of `electron-download` and tested your dockerfile and it works now. thanks for helping debug

**Comment by jclohmann** [comment]
@maxogden It's working for me, now. Thanks for the fix.

**Comment by askhogan** [comment]
Got it to work by doing chmod ~/.electron on mac OSX

**Comment by beakybal4** [comment]
Had this issue on electron-prebuilt@0.29.2  on OS X 10.10.4, deleted everything in ~/.electron and chmod 777 the directory and that fixed it.

**Comment by RnbWd** [comment]
I'm wonder why read/write permissions wouldn't work in the home directly? maybe dependent on user permissions and npm / node versions? 

`mkdirp` is a fairly straight forward:

> If opts.mode isn't specified, it defaults to 0777 & (~process.umask()).

```js
case 'ENOENT':
                mkdirP(path.dirname(p), opts, function (er, made) {
                    if (er) cb(er, made);
                    else mkdirP(p, opts, cb, made);
                });
                break;
 default:
                xfs.stat(p, function (er2, stat) {
                    // if the stat fails, then that's super weird.
                    // let the original error be the failure reason.
                    if (er2 || !stat.isDirectory()) cb(er, made)
                    else cb(null, made);
                });
                break;
```
... ????relevant code????....
```js

       case 'ENOENT' :
                made = sync(path.dirname(p), opts, made);
                sync(p, opts, made);
                break;

            // In the case of any other error, just see if there's a dir
            // there already.  If so, then hooray!  If not, then something
            // is borked.
            default:
                var stat;
                try {
                    stat = xfs.statSync(p);
                }
                catch (err1) {
                    throw err0;
                }
                if (!stat.isDirectory()) throw err0;
                break;
        }
```

Is `chmod 777` equivalent  `0777 & (~process.umask())`? Anything look weird in error handling? I can't tell :/

**Comment by pirafrank** [comment]
Hi guys, this issue still happens. It has just occurred on OS X 10.10.4 trying to install electron-prebuilt 0.30.3 globally with sudo. Below the full output.

```sh
francesco@Golden-Hind:~$ sudo npm i -g electron-prebuilt@0.30.3
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@0.30.3 postinstall /usr/local/lib/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.30.3-darwin-x64.zip
[============================================>] 100.0% of 37.13 MB (1.75 MB/s)
/usr/local/lib/node_modules/electron-prebuilt/install.js:15
  throw err
        ^
Error: EACCES, rename '/usr/local/lib/node_modules/electron-prebuilt/electron-tmp-download/electron-v0.30.3-darwin-x64.zip'
    at Error (native)
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "-g" "electron-prebuilt@0.30.3"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.30.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.30.3 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/francesco/npm-debug.log

```

I confirm that ```chmod 777 ~/.electron``` fixes this. It doesn't happen on Linux (at least elementary 0.2).

**Comment by maxogden** [comment]
@pirafrank can you try this?

```
mkdir test
cd test
npm init # use default values
npm i electron-prebuilt
cd node_modules/electron-prebuilt
npm link
```

my guess is your npm permissions are messed up in some way, but its hard to diagnose

**Comment by pirafrank** [comment]
I tried, you're right. I've then sanitised my node install basically uninstalling and reinstalling in ~ using nvm. sudo's not needed anymore. Thank you!

*For those reading this lately*
Check nvm install instruction in the readme of the repo. After a few commands you'll have a clean working installation of node. Backup your modules and remove any previous node trace first.

**Comment by fritx** [comment]
```plain
root@iZ94ilzkpk9Z:~/dev/wxbot# npm i -g electron-prebuilt
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine boom@2.9.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
/root/local/bin/electron -> /root/local/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@0.33.1 postinstall /root/local/lib/node_modules/electron-prebuilt
> node install.js

sh: 1: node: Permission denied

npm ERR! electron-prebuilt@0.33.1 postinstall: `node install.js`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.33.1 postinstall script.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/root/local/bin/node" "/root/local/bin/npm" "i" "-g" "electron-prebuilt"
npm ERR! cwd /root/dev/wxbot
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by fritx** [comment]
https://github.com/mafintosh/electron-prebuilt/issues/27#issuecomment-128842342 @maxogden 's answer works, thanks!

**Comment by gabrielaimeeg** [comment]
[#27 (comment)](https://github.com/mafintosh/electron-prebuilt/issues/27#issuecomment-101173390)  @greco 's answer worked for me, thank you!

**Comment by FWennerdahl** [comment]
Still having this problem, running `sudo npm install electron-prebuilt -g`.

Confirmed that removing the `~/.electron` folder prior to install solves this. It's not enough to remove the files, the actual folder must be removed.

**Comment by renanborgez** [comment]
Changing permissions ~/.electron to 777 works for me.

**Comment by geek1011** [comment]
These commands work for me:
````
sudo apt-get install -y nodejs-legacy nodejs npm
rm -rf ~/.electron
mkdir ~/.electron
chmod 777 ~/.electron/
sudo npm -g install electron-prebuilt
````

Explanation: 

 - `sudo apt-get install nodejs-legacy` enables use of the `node` command instead of just `nodejs`. The installer uses the node command
 - `rm -rf ~/.electron` removes the folder as mentioned above
 - `mkdir ~/.electron` creates the folder so it can be chmodded
 - `chmod 777 ~/.electron` sets the permissions to avoid the EACCES error
 - `sudo npm -g install electron-prebuilt` installs electron-prebuilt

**Comment by VitorLuizC** [comment]
```
C:\Users\Vitor Cavalcanti>npm install electron-prebuilt -g
C:\Users\Vitor Cavalcanti\AppData\Roaming\npm\electron -> C:\Users\Vitor Cavalcanti\AppData\Roaming\npm\node_modules\electron-prebuilt\cli.js

> electron-prebuilt@0.36.9 postinstall C:\Users\Vitor Cavalcanti\AppData\Roaming\npm\node_modules\electron-prebuilt
> node install.js

Downloading electron-v0.36.9-win32-x64.zip
Error: connect ETIMEDOUT 192.30.252.131:443

C:\Users\Vitor Cavalcanti\AppData\Roaming\npm\node_modules\electron-prebuilt\install.js:22
  throw err
  ^
 Error: connect ETIMEDOUT 192.30.252.131:443
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron-prebuilt" "-g"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.36.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.36.9 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Vitor Cavalcanti\npm-debug.log

```

**Comment by ngoldman** [comment]
@VitorLuizC that looks like a timeout error, please try the solution mentioned in #66.

**Comment by dukegod** [comment]
@mafintosh install the pkg 'sudo npm install electron-prebuilt -g'
it also console error log 'install.js:22' 
but deleting ~/.electron and try again, it works;
but when it download 60%, it stopped.

**Comment by lai32290** [comment]
I'm using Ubuntu x64, When using electron in my package dependency, returning fallowing error:

```
npm ERR! electron-prebuilt@1.2.7 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.2.7 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

**Comment by paran0a** [comment]
Can't install electron-prebuilt.

Using win10.

Error below

```
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1008:11)
    at TLSWrap.onread (net.js:563:26)
 [                ..] \ postinstall: info lifecycle electron-prebuilt@1.2.7~postinstall: Failed to exec postinnpm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MyName\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron-prebuilt" "-g"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@1.2.7 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@1.2.7 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\MyName\Documents\Projects\test\npm-debug.log
```

**Comment by zeke** [comment]
> Error: read ECONNRESET

@paran0a that looks like it may have been a network blip. Can you try again?

**Comment by jesobreira** [comment]
Hi, @maxogden 

> my guess is your npm permissions are messed up in some way, but its hard to diagnose

I found a way you can repeat the issue easily.

1. Create a new fresh Amazon AWS Ubuntu 14.04.5 LTS machine
2. Install Node and NPM following the docs at NodeJS official webpage:

```
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
sudo apt-get install -y build-essential nodejs
```

3. Try to install Electron

```
npm i electron -g
```

It will fail.

4. Install allowing unsafe perms:

```
sudo npm i -g electron --unsafe-perm=true
```

It works.

**Comment by capouch** [comment]
Your step 4 is the key for all the installs I have seen.

**Comment by jesobreira** [comment]
I've faced this issue in every single machine I've worked with Electron (Linux - different distros and versions - and OS X), so it's hard for me to believe that someone actually is able to install Electron without `--unsafe-perm=true`, just following the readme file.

I wonder if it should be defined as the "standard" way to install Electron or if we should check compatibility with npx, for example.

Just a ref: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by andrewhunter0** [comment]
用sudo npm install -g react-devtools安装，一直报错：
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/react-devtools/node_modules/electron/electron-tmp-download-62651-1553758792533'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.8.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


但是，我换成sudo yarn global add react-devtools命令就安装成功了。
