### ISSUE TITLE
Does this create the app?

### ISSUE THREAD

**Issue by iamdriz** [mafintosh/electron-prebuilt#35]
When I tried this all I got was the app running.. it didn't create anything anywhere for me to then distribute... should it create something? And if so where and how do I do this?

In the past I have just downloaded the latest release of atom-shell/electron and then just moved my /app folder into the resources folder for the .exe / .app and then renamed it and distributed.

Does this package offer any of that??

**Comment by maxogden** [comment]
nope see electron-packager for that

**Comment by iamdriz** [comment]
So to clarify... All this does is just run it for testing only? Nothing more!

**Comment by maxogden** [comment]
it's an automated way to install specific versions of electron on your computer for development, you can also manually download the zips if you want
