### ISSUE TITLE
app doesn't start

### ISSUE THREAD

**Issue by loveencounterflow** [mafintosh/electron-prebuilt#44]
i'm trying to do the basic first steps as outlined in ["Creating Desktop Apps with Electron" by Kyle Robinson Young](https://www.youtube.com/watch?v=ojX5yz35v4M) but i only get to the point where executing `electron .` should bring up an empty window. My `index.js` looks like this:
```js
var app           = require( 'app' );
var BrowserWindow = require( 'browser-window' );
var log           = console.log;

log( app );
log( process[ 'versions' ] );
app.on( 'ready', function(){
  log( "app ready" );
  var main_window = new BrowserWindow({
    width:    1200,
    height:    800,
  });
  var url = 'file://' + __dirname + '/index.html';
  main_window.loadUrl( url );
  } );

app.on( 'gpu-process-crashed',           function(){ log( 'gpu-process-crashed'           ); } );
app.on( 'select-certificate',            function(){ log( 'select-certificate'            ); } );
app.on( 'activate-with-no-open-windows', function(){ log( 'activate-with-no-open-windows' ); } );
app.on( 'before-quit',                   function(){ log( 'before-quit'                   ); } );
app.on( 'browser-window-blur',           function(){ log( 'browser-window-blur'           ); } );
app.on( 'browser-window-focus',          function(){ log( 'browser-window-focus'          ); } );
app.on( 'open-file',                     function(){ log( 'open-file'                     ); } );
app.on( 'open-url',                      function(){ log( 'open-url'                      ); } );
app.on( 'quit',                          function(){ log( 'quit'                          ); } );
app.on( 'ready',                         function(){ log( 'ready'                         ); } );
app.on( 'will-finish-launching',         function(){ log( 'will-finish-launching'         ); } );
app.on( 'will-quit',                     function(){ log( 'will-quit'                     ); } );
app.on( 'window-all-closed',             function(){ log( 'window-all-closed'             ); } );
```
i get to see the output from the two `console.log` calls, but neither the `ready` event handler nor any of the other event handlers gets called; instead, the process terminates. 

**Edit** i'm using `n` for keeping multiple versions of NodeJS/iojs and have set the global iojs version to `2.3.1`. Turns out when i start the bundled executable directly from the command line as `.../test-electron/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron`, the process exits with `Segmentation fault: 11`. Any ideas what could be going wrong here? BTW this is on OSX 10.8.4.

**Edit 2** this is getting a little weirder now: i downloaded the prebuilt binary zip from https://github.com/atom/electron/releases and overwrote the `Electron.app` that came with `npm install` with the one from the downloaded archive—and it works. Comparing the contents of the two (with DiffMerge) would appear to show that the only difference is that the version installed via `npm install` lacks a lot of language files like `...electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources/en.lproj/` and so on.

**Comment by RnbWd** [comment]
try changing the `electron-prebuilt` version for [package.json](https://github.com/shama/letswritecode/blob/master/creating-desktop-apps-with-electron/package.json) in the example to the latest version `0.29.2`:

```js
"devDependencies": {
    "electron-prebuilt": "^0.29.2"
  }
```

or just run `npm install --save-dev electron-prebuilt@latest`

**Comment by loveencounterflow** [comment]
I've already done that; the [relevant parts of `package.json`](https://github.com/loveencounterflow/test-electron/blob/master/package.json) look like
```
  "scripts": {
    "start": "electron .",
    "pack": "electron-packager . test-electron --platform=darwin,linux --arch=x64 --version=0.29.2 --overwrite --out=releases"
  },
  "devDependencies": {
    "electron-packager": "^5.0.1",
    "electron-prebuilt": "^0.29.2",
...
```
I've just checked again and can confirm that when i `git clone https://github.com/loveencounterflow/test-electron`, go into the folder and do `npm install`, then the app won't start on OSX. When i replace the contents of the `test-electron/node_modules/electron-prebuilt/dist` folder with the contents of `https://github.com/atom/electron/releases/download/v0.29.2/electron-v0.29.2-darwin-x64.zip`, i do get a running app.

So i installed `segfault-handler` and i now get this:

```
Uncaught Exception:
Error: Module version mismatch. Expected 44, got 14.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at bindings (/private/tmp/test-electron/node_modules/segfault-handler/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/private/tmp/test-electron/node_modules/segfault-handler/index.js:3:37)
    at Module._compile (module.js:428:26)
```

**Comment by RnbWd** [comment]
Have you tried [electron-rebuilt](https://github.com/paulcbetts/electron-rebuilt)? 

`Error: Module version mismatch.`

Electron uses it's own fork of `io.js`, but `npm` installs packages based on your local environment which doesn't always match up with the `electron` runtime, especially for packages written with binding in `c++` like [segfault-handler](https://www.npmjs.com/package/segfault-handler). Hopefully that solves the problem!

**Comment by loveencounterflow** [comment]
@RnbWd Here's a way to reproduce the issue:

```bash
git clone https://github.com/loveencounterflow/test-electron.git
cd test-electron/
git checkout a665d1
npm install
node_modules/.bin/electron-rebuild
npm run start
```
On my OSX 10.8.4, this finishes without opening a window; on my Linux Mint VM, it works as expected. After replacing the `Electron.app` in the `dist` folder of `electron-prebuilt` with the latest Electron releases download, it works on OSX, too, so i guess the problem should really be with the `.app` of the prebuild version.

**Comment by RnbWd** [comment]
Sounds like the file being downloaded is wrong... 

I'd recommend opening an issue with [electron-download](https://github.com/maxogden/electron-download), which just downloads & unzips the files hosted by [electron's official repo](https://github.com/atom/electron/releases). 

I'll also try testing it myself. Also delete the `~/.electron` folder if you haven't already. 

If you open a node repl, calling `os.arch()` and `os.platform()` *should* output `'x64` and `darwin` - just to make sure it's downloading the correct file. The `Electron.app` in `dist` *should* be identical to what you downloaded here `https://github.com/atom/electron/releases/download/v0.29.2/electron-v0.29.2-darwin-x64.zip` ... at least in theory.

**Comment by loveencounterflow** [comment]
`os.arch()` and `os.platform()` are `'x64'` and `'darwin'` as expected. 

Running `diff -r` against the cloned version of the app and my downloaded release does show lots of differences, all of them `.lproj` language files that are only present in the downloaded archive:

```
/tmp/test-electron ► diff -r node_modules/electron-prebuilt/dist/ ~/Downloads/electron-v0.29.2-darwin-x64.zip\ Folder/
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: am.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: ar.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: bg.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: bn.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: ca.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: cs.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: da.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: de.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: el.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: en.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: en_GB.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: es.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: es_419.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: et.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: fa.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: fi.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: fil.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: fr.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: gu.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: he.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: hi.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: hr.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: hu.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: id.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: it.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: ja.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: kn.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: ko.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: lt.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: lv.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: ml.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: mr.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: ms.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: nb.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: nl.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: pl.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: pt_BR.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: pt_PT.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: ro.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: ru.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: sk.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: sl.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: sr.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: sv.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: sw.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: ta.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: te.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: th.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: tr.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: uk.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: vi.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: zh_CN.lproj
Only in /Users/flow/Downloads/electron-v0.29.2-darwin-x64.zip Folder/Electron.app/Contents/Resources: zh_TW.lproj
```

i then deleted the `~/.electron` folder and the cloned app, re-did the installation and ran `diff` once more; turns out i get the exact same diffing results as shown above, so the `Electron.app` from `~/.electron/electron-v0.29.2-darwin-x64.zip` != the `Electron.app` from the releases page.

**Comment by RnbWd** [comment]
They're supposed to be identical... unless you're downloading from a mirror repo:

> You can set the ELECTRON_MIRROR env variable to use a custom base URL for grabbing electron zips. - [electron-download](https://github.com/maxogden/electron-download)

????? Sorry I can't help more

**Comment by maxogden** [comment]
gonna be honest, I read the thread multiple times and am not sure what the current issue is

**Comment by loveencounterflow** [comment]
yes it is confusing. 

I posted above how to reproduce the issue which essentially consists in `git clone`ing and `npm install`ing a sample app on both Linux and OSX. The app starts under Linux, but not under OSX; on OSX, `diff`ing the prebuilt app with a manually downloaded one gives the above output, which might be the cause of the error. 

One possible step to resolve this would be a friendly soul who tries to do the same and posts results here. If that should work on their OSX, chances are mine is borked; if that should fail on OSX but succeed on Linux, someone might come up with a theory where the difference comes from.

Otherwise we must close this as i'd prefer to wait for the next Electron release before trying again.

**Comment by loveencounterflow** [comment]
continued as #54
