### ISSUE TITLE
Hard Coded Version in install.js

### ISSUE THREAD

**Issue by 0x00A** [mafintosh/electron-prebuilt#5]
The version that `install.js` pulls down is [`hard coded`](https://github.com/mafintosh/atom-shell/blob/master/install.js#L11) to `0.18.0`, but the latest release is `0.19.5` which has lots of bug fixes. Maybe we could figure out what the latest version is and have it pull that?

**Comment by hij1nx** [comment]
hmm, downloads seem to be doing this redirect thing to aws that nugget doesn't seem to know how to handle.

**Comment by FWeinb** [comment]
Would you mind updating to the latest version of electron again?
