### ISSUE TITLE
Current version on OSX isn't executable by default

### ISSUE THREAD

**Issue by maxkorp** [mafintosh/electron-prebuilt#52]
When I download the current version (0.30.4), it's not executable by default. Trying to run the app just says that it could not be run. All of the executables (so `Electron.app/Contents/MacOS/electron`, `Electron.app/Contents/Frameworks/Electron\ Framework.framework\Electron Framework` and such are marked non executable. chmod +x fixes this. They are executable when downloaded using grunt-download-electron. Is this an issue here? or upstream with electron?

**Comment by mafintosh** [comment]
Just tried installing electron-prebuilt 0.30.4 and it was marked as executable for me. Does reinstall this problem for you?

**Comment by maxkorp** [comment]
Yeah, I had tried reinstalling a few times but no dice, but tried again today and it's working fine. Guessing something weird on my end. Thanks man.
