### ISSUE TITLE
Installing electron v0.33.0 failing on linux

### ISSUE THREAD

**Issue by FWeinb** [mafintosh/electron-prebuilt#59]
Just upgraded to electron v0.33.0 but the download is failing on linux x64. You can find an error log [here](https://travis-ci.org/FWeinb/electron-screenshot-service/builds/81249158#L171-L204).

**Comment by maxogden** [comment]
error is:

```
Error: GET https://github.com/atom/electron/releases/download/v0.33.0/electron-v0.33.0-linux-x64.zip returned 500
```

but https://github.com/atom/electron/releases/download/v0.33.0/electron-v0.33.0-linux-x64.zip works for me, so looks like a github issue

**Comment by mafintosh** [comment]
s3 had issues earlier today which might be why this was failing
