### ISSUE TITLE
No path.txt in electron-prebuilt folder

### ISSUE THREAD

**Issue by psciascia** [mafintosh/electron-prebuilt#76]
Newbie here. I'm trying to learn Electron, so  I grabbed a simple enough example online and installed electron-prebuilt (not using -g but --save-dev). As I try to run npm run start, I get infamous error:
ENOENT, no such file or directory '<root>/electron-prebuilt/path.txt' 
I Googles and found an issue within electron (not prebuilt):
https://github.com/atom/electron/issues/3563
It has been closed  but there are 2 comments, on saying not to install with -g (not my case) and the other suggesting the post be transfered here. I would  just like to know how this issue ended, because it is still one for me. I'm on a Window 7 64-bit.

**Comment by maxogden** [comment]
Hi @psciascia, can you look into your `./node_modules/electron-prebuilt` folder (that was created with you did `npm install --save-dev electron-prebuilt` and see if there is a `path.txt` file in there?

**Comment by psciascia** [comment]
Hi maxodgen, to answer your question, no there isn't. Actually that's the title of my post (No path.txt in electron-prebuilt folder)  :) 
What I do have in node_modules\electron-prebuilt are the following:
- another node_modules subfolder
- a test folder
- .npmignore
- .travis.yml
- cli.js
- CONTRIBUTING.md
- index.js
- install.js
- LICENSE
- package.json
- README.md

**Comment by psciascia** [comment]
I won't pretend to be an js expert (I'm more of a c++ programmer), but looking at install.js, I see this:
***********************************
// downloads if not cached
download({version: version, arch: process.env.npm_config_arch}, extractFile)

// unzips and makes path.txt point at the correct executable
function extractFile (err, zipPath) {
...
***********************************
I'm not sure what the "download" call actually  downloads, but from what I understand, it should be a zip file that contains path.txt.

So, using this logic (and the comment above 'download''), I figured I had something in my cache that prevents the download, and  it doesn't include path.txt.  So I deleted the folders created by npm install, cleared my cache and reinstalled. The result is what I have already posted. What I do not understand is that it should be throwing execptions and I do not see them. I don't how they are handled.

**Comment by maxogden** [comment]
@psciascia `path.txt` is created at install time: https://github.com/mafintosh/electron-prebuilt/blob/master/install.js#L32, `install.js` is executed using the `postinstall` hook of npm: https://github.com/mafintosh/electron-prebuilt/blob/master/package.json#L11

If you don't have a `path.txt` it means your computer didnt run the `postinstall` script, or it did run it but it never got the point where `path.txt` was created. To debug I would recommend trying to find out if this line gets executed, and if so what the value of the variables on this line are: https://github.com/mafintosh/electron-prebuilt/blob/master/install.js#L32

**Comment by psciascia** [comment]
Thanks again for your help. As I mentioned, I am pretty sure that line of code does not get executed and that's why I want to know if <zipPath> is actually downloaded.
Now this is where my amateurism will really show: How do I debug install.js?
If I add a few console.log lines to find out where the code goes -  or if I make any modifications to install.js, I lose them as soon as I run npm install because it will just be overwritten.
So how can I rerun mt modified install.js?

**Comment by maxogden** [comment]
@psciascia if you git clone a copy of the electron-prebuilt module you can do `cd electron-prebuilt` and just run `npm install --production` inside there to simulate `npm install electron-prebuilt`. if you omit `--production` it also installs `devDependencies` which shouldnt affect this, but `npm install --production` will do everything `npm install electron-prebuilt` does

**Comment by psciascia** [comment]
Alright @maxogden I was able to run my modified install.js (thanks!) and I can now confirm that not only does the line 
https://github.com/mafintosh/electron-prebuilt/blob/master/install.js#L32 
 **NOT** get executed, but the function extractFile does not even get called. I sprinkled some console.log lines everywhere and I know the this line gets executed:
https://github.com/mafintosh/electron-prebuilt/blob/master/install.js#L27
So I can now at least prove what I suspected. Any ideas why ?
One thing I tried was to echo the value of process.env.npm_config_arch and I get 'undefined'. This might explain why download does not get the file, thus not use the extractFile callback.

**Comment by maxogden** [comment]
@psciascia hmm weird, electron-download (https://github.com/maxogden/electron-download/blob/master/index.js) should always call the callback.

Can you try running this? (to enable the debug logging in electron-download)

```
DEBUG=electron-download node install.js 
```

Here's what I see for example (note I deleted my path.txt first, and verified it successfully got created after)

```
~/src/js/electron-prebuilt $  rm path.txt 
~/src/js/electron-prebuilt $  DEBUG=electron-download node install.js 
  electron-download info +0ms { cache: '/Users/max/.electron',
  filename: 'electron-v0.35.2-darwin-x64.zip',
  url: 'https://github.com/atom/electron/releases/download/v0.35.2/electron-v0.35.2-darwin-x64.zip' }
  electron-download zip exists +6ms /Users/max/.electron/electron-v0.35.2-darwin-x64.zip
~/src/js/electron-prebuilt $  cat path.txt 
/Users/max/src/js/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron
```

I'm using Node 4.0.0 and npm 2.14.2 on Mac OSX

**Comment by psciascia** [comment]
@maxogden  anything I have to install to set DEBUG? I'm running on Window 7 x64, and the command is not recognized.

**Comment by psciascia** [comment]
npm install electron-debug, maybe?

**Comment by maxogden** [comment]
@psciascia i'm not sure how to set environment variables on windows sorry

**Comment by substack** [comment]
I just ran into the same issue on linux installing friends (electron-prebuilt@0.34.2): 

```
Error: ENOENT: no such file or directory, open '/home/substack/projects/friends/node_modules/electron-prebuilt/path.txt'
```

**Comment by psciascia** [comment]
I attacked this from another angle this morning, and ran through installation on another computer that did not even have node.js on it. everything worked fine on that machine. 

And there's something I never notice on the the new  machine which I do not see on the problematic machine...
The download line

Downloading electron-v0.35.4-win32-x64.zip

The problematic machine jumps right in to the GET lines, and there are so many that they fly by without me reading them, and I see a few warnings flash by.

So I will be drastic, and reinstall node.js. and start all over to see what happens. 
Below is my full install trace in the new machine (on which the process worked.)

E:\DEV\Electron\ElectronExample>npm install --save-dev electron-prebuilt
-
> electron-prebuilt@0.35.4 postinstall E:\DEV\Electron\ElectronExample\node_modu
les\electron-prebuilt
> node install.js

Downloading electron-v0.35.4-win32-x64.zip
[============================================>] 100.0% of 49.16 MB (514.8 kB/s)
electron-prebuilt@0.35.4 node_modules\electron-prebuilt
├── extract-zip@1.2.0 (debug@0.7.4, async@0.9.0, mkdirp@0.5.0, yauzl@2.3.1, conc
at-stream@1.5.0)
└── electron-download@1.4.1 (path-exists@1.0.0, home-path@1.0.1, minimist@1.2.0,
 mkdirp@0.5.1, rc@1.1.5, debug@2.2.0, mv@2.1.1, nugget@1.6.0)

**Comment by psciascia** [comment]
Whoa, it is really not working out. Now I get nothing but errors, but I thing the most significat is:
Error: Registry returned 404 for GET on https://registry.npmjs.org/electron-prebuild
So evidently, if I can't connect, I won't GET anything. 
And all this worked on another machine 15 minutes ago.

**Comment by psciascia** [comment]
Sorry to have consumed so much of your time and thanks for the help @maxogden and @substack .
This turned out, though I can't prove it, to be a silly installation issue with node.js. After the reinstall (of node.js, then electron-prebuilt), everything worked. 
My guess is, since I had node.js for a while, that I may have been running a 32-bit version. I couldn't find the original .msi that I ran to install it. WIth the 64-bit msi, everything is honky-dory. I will close this issue. I can finally play with electron a bit.
Thanks again!

**Comment by maxogden** [comment]
@psciascia ahhhh crazy. glad you finally got to the bottom of it!

**Comment by JonathanPicques** [comment]
It sometimes happens when the postinstall hangs and you Ctrl+C it (because it's downloading a ~30Mb file)

**Comment by espring** [comment]
I had the same issue. 
`cd node_modules/electron-prebuilt && node install.js  `
fixed it.

**Comment by kyle-erin** [comment]
I had this problem when using the git bash instead of cmd on Windows 10. Using cmd made it work as intended.

**Comment by NHQ** [comment]
I ```cd```'d to ```node_modules/electron-prebuilt/``` and cast ```npm run postintstall```  :100:

**Comment by NHQ** [comment]
after attempting some solutions from this thread, I now get the following error::

```
error loading sodium bindings: Cannot find module 'chloridedown/build/Release/sodium'
falling back to javascript version.
/home/swarmbot/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory
/home/swarmbot/node_modules/libsodium/dist/modules/libsodium.js:14
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!ret&&filename!=nodePath["resolve"](filename)){
```

**Comment by basarat** [comment]
I ran into the same issue on mac osx. Did what substack did, deleted node_modules and ran `npm install again` :rose:

**Comment by shotlom** [comment]
Ok so @maxogden is there a security issue with using ```postinstall```? 

Following the security recommendation at https://www.kb.cert.org/vuls/id/319816 I installed electron-prebuilt with:

```
>npm i electron-prebuilt --save --ignore-scripts
```

I'm assuming that this will kill the ```postinstall``` install.js script responsible for path.txt.

So is there a work around from a security POV?

**Comment by brogmic** [comment]
For me solved with:
`npm i electron-prebuilt --save-dev`

👍

**Comment by karlito40** [comment]
I confirm `npm i electron-prebuilt --save-dev` solve the problem

**Comment by chucai** [comment]
I have some relative issue:

```
no such file or directory : electron/path.txt
```

For me solved with :
```
cd ./node_modules/electron && node install.js
```

I don't know the reason ~~~~~~~~

**Comment by toughthinktank** [comment]
Just go to the electron folder which should be ` cd /usr/local/lib/node_modules/electron` and run `sudo node install`
It actually gets stuck and throws an error because it does not get the permission to create the dist folder so running that script with sudo works fine.
