### ISSUE TITLE
Error: EEXIST: file already exists, symlink 'Versions/Current/Electron Framework'

### ISSUE THREAD

**Issue by gabriel** [mafintosh/electron-prebuilt#79]
It looks like electron-prebuilt doesn't like being electron-rebuild more than once?

Here is the output:
https://gist.github.com/gabriel/bf138b2d84d55f1d8168

If I manually `rm -rf node_modules/electron-prebuilt/dist`, running electron-rebuild works.

**Comment by mafintosh** [comment]
This is fixed in master. Will be released when there is a new version of electron
