### ISSUE TITLE
npm\atom-shell.cmd not working

### ISSUE THREAD

**Issue by juliankrispel** [mafintosh/electron-prebuilt#9]
This probably isn't really an issue with this project but npm on windows 8.1. But I think I have a better chance of resolving this with somebody who hasn't got 800 issues on there hands. I hope you don't mind, otherwise feel free to close this issue straight away.

On windows 8.1 in the folder ~\AppData\Roaming\npm there lie all the `.cmd` scripts to launch global executable npm packages including atom-shell.

This is the content for the atom-shell `.cmd` file:
```shell
@IF EXIST "%~dp0\/bin/bash.exe" (
  "%~dp0\/bin/bash.exe"  "%~dp0\node_modules\atom-shell\run.bat" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  /bin/bash  "%~dp0\node_modules\atom-shell\run.bat" %*
)
```

Windows will arrive at the last line in this script:

```shell
/bin/bash  "%~dp0\node_modules\atom-shell\run.bat" %*
```
and then fail, because there is no such thing as /bin/bash on windows?!?!?!

**Comment by maxogden** [comment]
Hmm I have no idea (and dont have a windows 8 environment to test in). Maybe a good starting point would be to find the source code that generates that `.cmd` file?

**Comment by bcomnes** [comment]
@juliankrispel What happens if you run it inside the shell provided by Git BASH from https://msysgit.github.io/ ?

**Comment by jdwilliams15** [comment]
I can confirm that this does not work on either my windows 7 system or my a windows 8 system. Used git bash, did 'npm install -g atom-shell'. The error message I get when I try to run is ' line 1: /node_modules/atom-shell/run.bat: No such file or directory'

**Comment by flying-circus** [comment]
C'mon guys current released electron.cmd doesn't work even if I run it under Github Shell environment!!!
If I change .cmd contents to:
`"%~dp0\node_modules\electron-prebuilt\run.bat"   %*`

works as it should!

**Comment by maxogden** [comment]
If any windows devs want to send a pull request that fixes this we would be happy to merge it. None of the current maintainers have time or expertise to debug windows support beyond CMD.EXE, which it currently works with.

**Comment by JamesKyburz** [comment]
Having a look at this, no solution yet. However we need [this electron windows fix](https://github.com/atom/electron/issues/1442) to be released too before everything will work.

**Comment by JamesKyburz** [comment]
@flying-circus npm uses [cmd-shim](http://npm.im/cmd-shim) to create the cmd file.

I am looking into how the shebang handling is done for windows.

**Comment by jugglingnutcase** [comment]
i'm seeing the same issue and i'm happy to help resolve it, but i'm not quite understanding what's happening and would like to before i propose any changes.

Dumb question here: how does the `electron.bat` file get into the .bin folder? Is that the cmd-shim's responsibility? Let me explain myself if that's not very clear... i'm seeing two different batch files at play.

One batch file, `~\AppData\npm\Roaming\electron.cmd`, doesn't work for me, and contains:

```
@IF EXIST "%~dp0\/bin/bash.exe" (
  "%~dp0\/bin/bash.exe"  "%~dp0\node_modules\electron-prebuilt\run.bat" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  /bin/bash  "%~dp0\node_modules\electron-prebuilt\run.bat" %*
)
```

The `~\AppData\npm\Roaming\node_modules\electron-prebuilt\run.bat` file contains:

```
"C:\Users\james_000\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\electron.exe" %*
```

The first batch file doesn't work for me, the second works fine. Is it possible to get that second batch file into the first's location? Is that just something that needs to be added to the install.js script or is there some deeper fix neede?

:warning: i've only ever consumed npm packages, never generated one myself, so sorry if there's obvious knowledge i'm missing here. :warning:

**Comment by JamesKyburz** [comment]
@jugglingnutcase Thanks! I'm very close to sending the pull request. The issue is that the shebang is determined before `install.js` runs. And the run.bat file prior to install running has a bash shebang hence the /bin/bash in the cmd file. `cmd-shim` doesn't create an if statement with a blank shebang.

I have fixed this with a simple preinstall step.

It's working in a cmd environment but not when using git bash in windows.

**Comment by jugglingnutcase** [comment]
i had the same fix in progress :smile: i'll wait for your fix to hit then.

**Comment by JamesKyburz** [comment]
@jugglingnutcase :)

**Comment by jugglingnutcase** [comment]
Did you submit it here?

**Comment by JamesKyburz** [comment]
I will associate the pull request fixing this. Not submitted yet due to the git bash issue.

**Comment by jugglingnutcase** [comment]
@JamesKyburz i just tested your fix and it works fine for me in GitHub for Windows git bash:

```
james_000@NEO ~/Documents/src/test-electron-prebuilt/node_modules/.bin
$ cmd "/c electron.cmd"

c:\Users\james_000\Documents\src\test-electron-prebuilt\node_modules\.bin>"c:\Users\james_000\Documents\src\test-electron-prebuilt\node_modules\.bin\\..\electron-prebuilt\run.bat"

c:\Users\james_000\Documents\src\test-electron-prebuilt\node_modules\.bin>"c:\Users\james_000\Documents\src\test-electron-prebuilt\node_modules\electron-prebuilt\dist\electron.exe"
[12384:0421/132342:INFO:renderer_main.cc(212)] Renderer process started
```

**Comment by JamesKyburz** [comment]
@jugglingnutcase Nice! FYI I'm force pushing like a made man at the mo ;)

Basically git bash needs the shebang and cmd doesn't. Still playing around to be sure.

**Comment by JamesKyburz** [comment]
@jugglingnutcase I sent the pull request now.

Not happy with having to check the process.title for git bash but should work. cygwin will never work anyways ;)

I have verified that it works in cmd.exe but as I am suffering from [this issue](https://github.com/atom/electron/issues/1442) preventing me to checking the git bash env.

Could you please check it works in your git bash environment?

**Comment by JamesKyburz** [comment]
@jugglingnutcase never mind the process.title is npm when npm is installing.......Will look at this again tomorrow.

**Comment by JamesKyburz** [comment]
OK done now. All the sane things failed in windows like echo $SHELL or checking for the presence of /bin/bash.

I came up with process.env.TERM this is falsy in cmd.exe and set to something otherwise.

I have verified both cmd.exe and git bash on my virtual machine running win 8.1.

**Comment by JamesKyburz** [comment]
Please see pull request for details. I replaced run.bat with cli.js and removed the preinstall step.
