### ISSUE TITLE
Ubuntu Missing dependencies?

### ISSUE THREAD

**Issue by kevzettler** [mafintosh/electron-prebuilt#92]
```
/usr/local/lib/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
/usr/local/lib/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory
/usr/local/lib/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory
/usr/local/lib/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

**Comment by maxogden** [comment]
hmm weird. seems like an electron issue

**Comment by zoobab** [comment]
I had to install those packages on Ubuntu Xenial to have electron-prebuilt version v0.33.2 (I am testing the more recent versions soon):

$ apt-get install libgtkextra-dev libgconf2-dev libnss3 libasound2 libxtst-dev

Why now shipping a fully static binary that works on any distro?

**Comment by ekristen** [comment]
Any traction on this?

**Comment by maxogden** [comment]
nobody experiencing the problem has verified if its an electron issue, that would be a good place to start

**Comment by zoobab** [comment]
You mean electron vs electron-prebuilt? I mean a dependency to the extreme is glibc if you don't provide a fully static binary, which is still the way to ship software if you don't want to deal with all the distros dependencies.

**Comment by maxogden** [comment]
reminder that this repo is *not* electron. it's just the thing that downloads electron. issues about packaging electron are not related to this repo

**Comment by kevzettler** [comment]
apparently this has been fixed in electron https://github.com/atom/electron/issues/4341
